export const GET_ITINERARY_REQUEST = 'GET_ITINERARY_REQUEST'
export const GET_ITINERARY_SUCCESS = 'GET_ITINERARY_SUCCESS'
export const GET_ITINERARY_FAILURE = 'GET_ITINERARY_FAILURE'


export const SAVE_STATE = 'SAVE_STATE'
export const RESTORE_STATE = 'RESTORE_STATE'

export const TOGGLE_DELETE_BUTTON = 'TOGGLE_DELETE_BUTTON'
