export const GET_ITINERARY_REQUEST = 'GET_ITINERARY_REQUEST'
export const GET_ITINERARY_SUCCESS = 'GET_ITINERARY_SUCCESS'
export const GET_ITINERARY_FAILURE = 'GET_ITINERARY_FAILURE'


export const SAVE_STATE = 'SAVE_STATE'
export const RESTORE_STATE = 'RESTORE_STATE'

export const TOGGLE_DELETE_BUTTON = 'TOGGLE_DELETE_BUTTON'

export const ADD_ITINERARY_ITEM = 'ADD_ITINERARY_ITEM'
export const DELETE_ITINERARY_ITEM = 'DELETE_ITINERARY_ITEM'
export const EDIT_ITINERARY = 'EDIT_ITINERARY'

export const SWITCH_TO_PAGE = 'SWITCH_TO_PAGE'

export const MOCK_DATA_GEO_ID = 'MOCK_DATA_GEO_ID'
export const MOCK_DATA_ITEM = 'MOCK_DATA_ITEM'
